import { Inter } from "next/font/google";
import "../globals.css";
// import Provider from "@/context/Provider";
import { ThemeProvider } from "@/components/ThemeProvider";
import Header from "@/components/Header";
import ToasterContext from "@/context/ToasterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Provider> */}
        <body className={inter.className}>
          <ToasterContext />
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            {children}
          </ThemeProvider>
        </body>
      {/* </Provider> */}
    </html>
  );
}
